### ISSUE TITLE
DocumentClientFactory should use IServicesConfig in constructor

### ISSUE THREAD

**Issue by zhang-hua** [Azure/pcs-storage-adapter-java#50]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

https://github.com/Azure/pcs-storage-adapter-java/blob/master/app/com/microsoft/azure/iotsolutions/storageadapter/services/wrappers/DocumentClientFactory.java#L28

**Comment by jwendl** [comment]
Hello @zhang-hua - would this also impact being able to do the following?

``` bash
export PCS_STORAGEADAPTER_CONTAINER_NAME="..."
./scripts/build
```

And getting the error

```
[info] Test com.microsoft.azure.iotsolutions.storageadapter.service.DocDBKeyValueContainerTest.putTest started
[error] Test com.microsoft.azure.iotsolutions.storageadapter.service.DocDBKeyValueContainerTest.putTest failed: com.microsoft.azure.iotsolutions.storageadapter.services.exceptions.InvalidConfigurationException: DocumentDB configuration error, took 0.223 sec
[error] c.m.a.i.s.s.w.DocumentClientFactory - Config: 'docDbEndpoint'=, 'docDbKey'=, 'databaseName'=pcs-storage, 'collectionId'=pcs-storage
[error]     at com.microsoft.azure.iotsolutions.storageadapter.services.wrappers.DocumentClientFactory.<init>(DocumentClientFactory.java:41)
[error] c.m.a.i.s.s.w.DocumentClientFactory - Config: 'docDbEndpoint'=, 'docDbKey'=, 'databaseName'=pcs-storage, 'collectionId'=pcs-storage
[error] c.m.a.i.s.s.w.DocumentClientFactory - Config: 'docDbEndpoint'=, 'docDbKey'=, 'databaseName'=pcs-storage, 'collectionId'=pcs-storage
[error] c.m.a.i.s.s.w.DocumentClientFactory - Config: 'docDbEndpoint'=, 'docDbKey'=, 'databaseName'=pcs-storage, 'collectionId'=pcs-storage
[error]     at com.microsoft.azure.iotsolutions.storageadapter.service.DocDBKeyValueContainerTest.setUp(DocDBKeyValueContainerTest.java:39)
[error]     ...
[error] Test com.microsoft.azure.iotsolutions.storageadapter.service.DocDBKeyValueContainerTest.putTest failed: java.lang.NullPointerException: null, took 0.224 sec
[error]     at com.microsoft.azure.iotsolutions.storageadapter.service.DocDBKeyValueContainerTest.tearDown(DocDBKeyValueContainerTest.java:47)
[error]     ...
```

Or is this unrelated?

**Comment by zhang-hua** [comment]
@jwendl , it is unrelated. please export another environment variable for document db connection before running tests:
```
export PCS_STORAGEADAPTER_DOCUMENTDB_CONNSTRING=""
```
